//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int AttendanceId { get; set; }
        public int StudentId { get; set; }
        public System.DateTime Date { get; set; }
        public string SessionFirst { get; set; }
        public string SessionSecond { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
