//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacultyClassAllocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public FacultyClassAllocation()
        //{
        //    this.FacultyAllocation = new HashSet<FacultyClassAllocation>();
           
        //}
        public int FacultyAllocationId { get; set; }
        public Nullable<int> FacultyId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public System.TimeSpan Class_Start_Time { get; set; }
        public System.TimeSpan Class_End_Time { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ClassMaster ClassMaster { get; set; }
        public virtual FacultyMaster FacultyMaster { get; set; }
        public virtual SubjectMaster SubjectMaster { get; set; }

        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<FacultyClassAllocation> FacultyAllocation { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    }
}
