//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRegistration
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
        public string SaltKey { get; set; }
        public int RoleId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> Updatedon { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    }
}
